### ISSUE TITLE
How to use it with umu-launcher flatpak

### ISSUE THREAD

**Issue by Faugus** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#204]
I'm trying to get gamescope flatpak to work with umu-launcher flatpak.
The same problem occurs when I try to use gamescope flatpak with steam flatpak.
I tested your build on steam and gamescope worked correctly.

Is it possible to do the same with umu-launcher flatpak?
umu-launcher allows you to use a specific version of Proton by putting the path in the PROTONPATH variable.

**Comment by ChrisHobday** [comment]
If I understand correctly, this isn't an issue with this Flatpak or Proton-GE, but instead a query about how this Flatpak works correctly with the Gamescope + Steam Flatpaks, and if it can be adapted to allow the umu-launcher Flatpak and Gamescope to work correctly together, correct?

I'm not exactly sure what problem you are running into, but if it is similar to this issue https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/issues/199 , it's apparently caused because of the way Steam's pressure-vessel works in a Flatpak, I'm not entirely sure. Either way, this Flatpak ultimately works correctly with the Gamescope + Steam Flatpaks because of the location Proton-GE is installed to in the Steam Flatpak, namely the Flatpak installation directory /app/share/steam/compatibilitytools.d/, this is achieved by designating the runtime as com.valvesoftware.Steam in the manifest. While installing manually or with ProtonUp-Qt, places Proton-GE in the user directory ~/.var/app/com.valvesoftware.Steam/.steam/root/compatibilitytools.d/.

Where is the umu-launcher Flatpak you are using? The last time I was messing with it was a release candidate version, and the new releases don't seem to have a Flatpak. Unless you are building it yourself with this https://github.com/Open-Wine-Components/umu-launcher/tree/main/packaging/flatpak?

Hopefully this helps, if I misunderstood your issue let me know.

**Comment by Faugus** [comment]
> If I understand correctly, this isn't an issue with this Flatpak or Proton-GE

Exactly, there's nothing wrong with them.
I'm just asking if there's a way to make your Proton-GE build work with umu-launcher flatpak.

> Unless you are building it yourself

Yes, I'm building it.

If you want to test it, install the flatpak and run:
```
flatpak run --comand=sh --devel org.openwinecomponents.umu.umu-launcher
```
Then run something like:
```
GAMEID=0 PROTONPATH=/path/to/a/proton/build gamescope -W 1920 -H 1080 -- /app/bin/umu-run "/some/windows/exe"
```

**Comment by ChrisHobday** [comment]
So I think what you want is to use this Flatpak's installation of Proton-GE in the PROTONPATH of that last command, right?

If that is the case you could do that by giving the umu-launcher Flatpak filesystem access to /var/lib/flatpak, and use PROTONPATH=/var/lib/flatpak/runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable/active/files. (This also requires that this Flatpak is installed system-wide and not with the --user flag).

There may be a better way to do this, as this is a pretty hacky solution, and I'm not sure if it will fix the problems you are having with Gamescope.

**Comment by Faugus** [comment]
It works, but it doesn't fix the gamescope problem.
Thanks anyways.
