### ISSUE TITLE
Latest update shows Mono install prompt

### ISSUE THREAD

**Issue by SuNNjek** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#79]
After updating to the GE-Proton7-8 flatpak yesterday I noticed that when I first started Steam or any game I got the Wine Mono install prompt. This only happened once for each game though, any subsequent launches don't show it anymore. When I tried to install it, I got a checksum error, but the game started anyway (and everything worked). When I just click cancel on the install prompt, the game also just starts.

**Comment by n00mkrad** [comment]
I have installed multiple GE versions using ProtonUp-Qt on Steam Deck and get this annoying popup every time I start desktop mode.

How do I figure out which one causes it?

**Comment by Lctrs** [comment]
This software doesn't install Proton-GE from this flatpak. You'll have to report this to ProtonUp-Qt developer.

**Comment by Lctrs** [comment]
Currently, we install the same wine mono version as the one referenced upstream. So you won't have this prompt.

**Comment by Lctrs** [comment]
This prompt appears when we don't install the same version, which happens when we miss the bump on upstream side.

**Comment by n00mkrad** [comment]
> This software doesn't install Proton-GE from this flatpak. You'll have to report this to ProtonUp-Qt developer.

So this message is caused by ProtonUp-Qt?

My point is that I get this message and have no idea where it's coming from, I only found this issue/thread by googling. 

I was using ProtonUp-Qt for weeks without issues, now suddenly I get this popup and don't know if it's caused by a ProtonUp-Qt update, a specific ProtonGE installation, or something entirely different.
